//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pluto.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pluto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EVALUATION.
        /// </summary>
        internal static string FILE_EVALUATION {
            get {
                return ResourceManager.GetString("FILE_EVALUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PHOTO.
        /// </summary>
        internal static string FILE_PHOTO {
            get {
                return ResourceManager.GetString("FILE_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PHOTOCOPIE_PIECE_IDENTITE_PREINSCRIPTION.
        /// </summary>
        internal static string FILE_PHOTOCOPIE_PIECE_IDENTITE_PREINSCRIPTION {
            get {
                return ResourceManager.GetString("FILE_PHOTOCOPIE_PIECE_IDENTITE_PREINSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PHOTOCOPIE_PREINSCRIPTION_ATTESTATION.
        /// </summary>
        internal static string FILE_PHOTOCOPIE_PREINSCRIPTION_ATTESTATION {
            get {
                return ResourceManager.GetString("FILE_PHOTOCOPIE_PREINSCRIPTION_ATTESTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PHOTOCOPIE_RELEVE_NOTE_PREINSCRIPTION.
        /// </summary>
        internal static string FILE_PHOTOCOPIE_RELEVE_NOTE_PREINSCRIPTION {
            get {
                return ResourceManager.GetString("FILE_PHOTOCOPIE_RELEVE_NOTE_PREINSCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PIECE.
        /// </summary>
        internal static string FILE_PIECE {
            get {
                return ResourceManager.GetString("FILE_PIECE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TD.
        /// </summary>
        internal static string FILE_TD {
            get {
                return ResourceManager.GetString("FILE_TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TP.
        /// </summary>
        internal static string FILE_TP {
            get {
                return ResourceManager.GetString("FILE_TP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PHOTO_PREINSCRIPTION.
        /// </summary>
        internal static string PHOTO_PREINSCRIPTION {
            get {
                return ResourceManager.GetString("PHOTO_PREINSCRIPTION", resourceCulture);
            }
        }
    }
}
